export const ELEC_SIZE = 40
export const CANVAS_WIDTH = 10
export const CANVAS_HEIGHT = 10
export const CANVAS_TRUE_WIDTH = CANVAS_WIDTH * ELEC_SIZE
export const CANVAS_TRUE_HEIGHT = CANVAS_HEIGHT * ELEC_SIZE