export const ELEC_SIZE = 40;
export const CANVAS_WIDTH = 26;
export const CANVAS_HEIGHT = 12;
export const CANVAS_TRUE_WIDTH = CANVAS_WIDTH * ELEC_SIZE;
export const CANVAS_TRUE_HEIGHT = CANVAS_HEIGHT * ELEC_SIZE;
export const MAX_NUM_COMBINES = CANVAS_WIDTH * CANVAS_HEIGHT / 2;
